name: Build/release PoE2 Kakao Launcher

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: yarn run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
